[package]
org = "ballerinax"
name = "PatientMatcher_Template"
displayName = "Patient Matcher Template"
description = "Exposes Patient Matching Feature as managed APIs"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Patient Matching"]
distribution = "2201.7.0"
repository = "https://github.com/wso2/open-healthcare-choreo-accelerators"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"

[persist]
datastore = "mysql"
module = "patient_matching_usecase"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4utils.patientmatching"
version = "1.0.0"
repository = "local"