[package]
org = "ballerinax"
name = "health.fhir.templates.r4.fhirpath_api"
displayName = "FHIRPATH API"
description = "Exposes FHIRPATH Processing Engine as managed APIs"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "FHIRPATH"]
version = "1.0.0"
distribution = "2201.7.0"
template = true
repository="https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4utils.fhirpath"
version = "1.1.0"
