[package]
org = "wso2"
name = "MetadataService"
version = "2.0.0"
distribution = "2201.7.0"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","Metadata"]

[build-options]
observabilityIncluded = true
